services:
  my-nginx:
    image: 925047940866.dkr.ecr.ap-southeast-2.amazonaws.com/nginx:latest
    # build:
    # context: ./nginx
    # dockerfile: Dockerfile
    container_name: nginx-container
    ports:
    - "80:80"
    volumes:
    - /home/ec2-user/nginx/html:/usr/share/nginx/html:ro
    # - /home/ec2-user/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    # - /home/ec2-user/nginx/logs:/var/log/nginx
    restart: always
    networks:
    - public-subnet
      # aliases:
      #   - nginx

  my-fastapi:
    image: 925047940866.dkr.ecr.ap-southeast-2.amazonaws.com/fastapi:latest
    container_name: fastapi-container
    ports:
    - "8000:8000"
    volumes:
    - /home/ec2-user/fastapi/app:/app:ro
    restart: always
    networks:
    - public-subnet

networks:
  public-subnet:
    driver: bridge
