name: Build and Deploy to AWS ASG via CodeDeploy
on:
  push:
    branches: [main]
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
  CODE_DEPLOY_APP_NAME: ${{ secrets.CODE_DEPLOY_APP_NAME }}
  CODE_DEPLOY_GROUP_APP_NAME: ${{ secrets.CODE_DEPLOY_GROUP_APP_NAME }}

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # 1. AWS 자격 증명 설정 (ECR 로그인 전에 수행)
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # 2. ECR 로그인
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # 3. ECR에 Docker 이미지 빌드 및 푸시
    - name: Build and Push Docker image to ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # docker build의 마지막 마침표(.)는 context경로를 의미
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
                     -t $ECR_REGISTRY/$ECR_REPOSITORY:latest \
                     -f ./nginx/Dockerfile ./nginx
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

    # 4. (중요)Zip 압축 단계 전에 chmod +x 추가
    # 5. CodeDeploy 배포 번들 생성 (appspec.yml과 scripts 디렉토리만 zip)
    # 6. 배포 번들 S3 업로드
    # 7. CodeDeploy 배포 생성